defaults: &defaults
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: postgres
  password: postgres
  host: localhost
  port: 5432
    
development: 
  database: travel_development
  <<: *defaults 

production:
  database: travel_production
  <<: *defaults
#   username: ENV["database_username"]
#   password: ENV["database_password"]
  
